### ISSUE TITLE
Add a verbose flag

### ISSUE THREAD

**Issue by SecretUnicorn** [albertodonato/sshoot#11]
Is there a way to add a verbose option to sshoot? I am simply stuck at 'Profile failed to start' and would really know why.

```shell
sshoot start profileX
[local sudo] Password:
Profile failed to start:
```

**Comment by BapRx** [comment]
Since `sshoot` runs `sshuttle` as a daemon, the logs are sent directly to syslog instead of stderr: https://github.com/sshuttle/sshuttle/blob/f8086dfa590f742561ffc1f4b4363da3f3cf4069/sshuttle/client.py#L77-L79

The logs are normally located at `/var/log/syslog`, I created a PR to print this information when the error message cannot be retrieved from stderr.
